/**
 * BookmarkResponseMessage automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.sdkfabric.twitter;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
public class BookmarkResponseMessage {
    private Boolean bookmarked;
    @JsonSetter("bookmarked")
    public void setBookmarked(Boolean bookmarked) {
        this.bookmarked = bookmarked;
    }
    @JsonGetter("bookmarked")
    public Boolean getBookmarked() {
        return this.bookmarked;
    }
}
