/**
 * BookmarkResponse automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.sdkfabric.twitter;

import com.fasterxml.jackson.annotation.*;

public class BookmarkResponse {
    private Bookmark data;

    @JsonSetter("data")
    public void setData(Bookmark data) {
        this.data = data;
    }

    @JsonGetter("data")
    public Bookmark getData() {
        return this.data;
    }
}

