/**
 * Bookmark automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.sdkfabric.twitter;

import com.fasterxml.jackson.annotation.*;

public class Bookmark {
    @JsonPropertyDescription("Indicates whether the user bookmarks the specified Tweet as a result of this request.")
    private Boolean bookmarked;

    @JsonSetter("bookmarked")
    public void setBookmarked(Boolean bookmarked) {
        this.bookmarked = bookmarked;
    }

    @JsonGetter("bookmarked")
    public Boolean getBookmarked() {
        return this.bookmarked;
    }
}

