/**
 * BookmarkResponse automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.sdkfabric.twitter;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;
public class BookmarkResponse {
    private BookmarkResponseMessage data;
    @JsonSetter("data")
    public void setData(BookmarkResponseMessage data) {
        this.data = data;
    }
    @JsonGetter("data")
    public BookmarkResponseMessage getData() {
        return this.data;
    }
}
