/**
 * Error automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.sdkfabric.twitter;

import com.fasterxml.jackson.annotation.*;

public class Error {
    private String type;
    private String title;
    private Integer status;
    private String detail;

    @JsonSetter("type")
    public void setType(String type) {
        this.type = type;
    }

    @JsonGetter("type")
    public String getType() {
        return this.type;
    }

    @JsonSetter("title")
    public void setTitle(String title) {
        this.title = title;
    }

    @JsonGetter("title")
    public String getTitle() {
        return this.title;
    }

    @JsonSetter("status")
    public void setStatus(Integer status) {
        this.status = status;
    }

    @JsonGetter("status")
    public Integer getStatus() {
        return this.status;
    }

    @JsonSetter("detail")
    public void setDetail(String detail) {
        this.detail = detail;
    }

    @JsonGetter("detail")
    public String getDetail() {
        return this.detail;
    }
}

