/**
 * Errors automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.sdkfabric.twitter;

import com.fasterxml.jackson.annotation.*;

public class Errors {
    private java.util.List<Error> errors;

    @JsonSetter("errors")
    public void setErrors(java.util.List<Error> errors) {
        this.errors = errors;
    }

    @JsonGetter("errors")
    public java.util.List<Error> getErrors() {
        return this.errors;
    }
}

