/**
 * Fields automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.sdkfabric.twitter;

import com.fasterxml.jackson.annotation.*;

public class Fields {
    private String mediaFields;
    private String placeFields;
    private String pollFields;
    private String tweetFields;
    private String userFields;

    @JsonSetter("media.fields")
    public void setMediaFields(String mediaFields) {
        this.mediaFields = mediaFields;
    }

    @JsonGetter("media.fields")
    public String getMediaFields() {
        return this.mediaFields;
    }

    @JsonSetter("place.fields")
    public void setPlaceFields(String placeFields) {
        this.placeFields = placeFields;
    }

    @JsonGetter("place.fields")
    public String getPlaceFields() {
        return this.placeFields;
    }

    @JsonSetter("poll.fields")
    public void setPollFields(String pollFields) {
        this.pollFields = pollFields;
    }

    @JsonGetter("poll.fields")
    public String getPollFields() {
        return this.pollFields;
    }

    @JsonSetter("tweet.fields")
    public void setTweetFields(String tweetFields) {
        this.tweetFields = tweetFields;
    }

    @JsonGetter("tweet.fields")
    public String getTweetFields() {
        return this.tweetFields;
    }

    @JsonSetter("user.fields")
    public void setUserFields(String userFields) {
        this.userFields = userFields;
    }

    @JsonGetter("user.fields")
    public String getUserFields() {
        return this.userFields;
    }
}

