/**
 * HideReplyUpdate automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.sdkfabric.twitter;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;
public class HideReplyUpdate {
    private boolean hidden;
    @JsonSetter("hidden")
    public void setHidden(boolean hidden) {
        this.hidden = hidden;
    }
    @JsonGetter("hidden")
    public boolean getHidden() {
        return this.hidden;
    }
}
