/**
 * HideReplyUpdate automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.sdkfabric.twitter;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
public class HideReplyUpdate {
    private Boolean hidden;
    @JsonSetter("hidden")
    public void setHidden(Boolean hidden) {
        this.hidden = hidden;
    }
    @JsonGetter("hidden")
    public Boolean getHidden() {
        return this.hidden;
    }
}
