/**
 * LikeResponse automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.sdkfabric.twitter;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;
public class LikeResponse {
    private LikeResponseMessage data;
    @JsonSetter("data")
    public void setData(LikeResponseMessage data) {
        this.data = data;
    }
    @JsonGetter("data")
    public LikeResponseMessage getData() {
        return this.data;
    }
}
