/**
 * LikeResponseMessage automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.sdkfabric.twitter;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;
public class LikeResponseMessage {
    private String liked;
    @JsonSetter("liked")
    public void setLiked(String liked) {
        this.liked = liked;
    }
    @JsonGetter("liked")
    public String getLiked() {
        return this.liked;
    }
}
