/**
 * LikeResponse automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.sdkfabric.twitter;

import com.fasterxml.jackson.annotation.*;

public class LikeResponse {
    private Like data;

    @JsonSetter("data")
    public void setData(Like data) {
        this.data = data;
    }

    @JsonGetter("data")
    public Like getData() {
        return this.data;
    }
}

