/**
 * SingleTweet automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.sdkfabric.twitter;

import com.fasterxml.jackson.annotation.*;

public class SingleTweet {
    private String tweetId;

    @JsonSetter("tweet_id")
    public void setTweetId(String tweetId) {
        this.tweetId = tweetId;
    }

    @JsonGetter("tweet_id")
    public String getTweetId() {
        return this.tweetId;
    }
}

