/**
 * TweetCreateResponse automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.sdkfabric.twitter;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
public class TweetCreateResponse {
    private TweetCreate data;
    @JsonSetter("data")
    public void setData(TweetCreate data) {
        this.data = data;
    }
    @JsonGetter("data")
    public TweetCreate getData() {
        return this.data;
    }
}
