/**
 * TweetCollection automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.sdkfabric.twitter;

import com.fasterxml.jackson.annotation.*;

public class TweetCollection {
    private java.util.List<TweetDetails> data;

    @JsonSetter("data")
    public void setData(java.util.List<TweetDetails> data) {
        this.data = data;
    }

    @JsonGetter("data")
    public java.util.List<TweetDetails> getData() {
        return this.data;
    }
}

