/**
 * TweetDeleteResponse automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.sdkfabric.twitter;

import com.fasterxml.jackson.annotation.*;

public class TweetDeleteResponse {
    private TweetDelete data;

    @JsonSetter("data")
    public void setData(TweetDelete data) {
        this.data = data;
    }

    @JsonGetter("data")
    public TweetDelete getData() {
        return this.data;
    }
}

