/**
 * TweetEntityResponse automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.sdkfabric.twitter;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;
public class TweetEntityResponse {
    private TweetDetails data;
    @JsonSetter("data")
    public void setData(TweetDetails data) {
        this.data = data;
    }
    @JsonGetter("data")
    public TweetDetails getData() {
        return this.data;
    }
}
