/**
 * TweetDeleteResponse automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.sdkfabric.twitter;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;
public class TweetDeleteResponse {
    private TweetDeleteResponseMessage data;
    @JsonSetter("data")
    public void setData(TweetDeleteResponseMessage data) {
        this.data = data;
    }
    @JsonGetter("data")
    public TweetDeleteResponseMessage getData() {
        return this.data;
    }
}
