/**
 * Tweet automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.sdkfabric.twitter;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;
public class Tweet {
    private String directMessageDeepLink;
    private boolean forSuperFollowersOnly;
    private TweetGeo geo;
    private TweetMedia media;
    private TweetPoll poll;
    private String quoteTweetId;
    private TweetReply reply;
    private String replySettings;
    private String text;
    @JsonSetter("direct_message_deep_link")
    public void setDirectMessageDeepLink(String directMessageDeepLink) {
        this.directMessageDeepLink = directMessageDeepLink;
    }
    @JsonGetter("direct_message_deep_link")
    public String getDirectMessageDeepLink() {
        return this.directMessageDeepLink;
    }
    @JsonSetter("for_super_followers_only")
    public void setForSuperFollowersOnly(boolean forSuperFollowersOnly) {
        this.forSuperFollowersOnly = forSuperFollowersOnly;
    }
    @JsonGetter("for_super_followers_only")
    public boolean getForSuperFollowersOnly() {
        return this.forSuperFollowersOnly;
    }
    @JsonSetter("geo")
    public void setGeo(TweetGeo geo) {
        this.geo = geo;
    }
    @JsonGetter("geo")
    public TweetGeo getGeo() {
        return this.geo;
    }
    @JsonSetter("media")
    public void setMedia(TweetMedia media) {
        this.media = media;
    }
    @JsonGetter("media")
    public TweetMedia getMedia() {
        return this.media;
    }
    @JsonSetter("poll")
    public void setPoll(TweetPoll poll) {
        this.poll = poll;
    }
    @JsonGetter("poll")
    public TweetPoll getPoll() {
        return this.poll;
    }
    @JsonSetter("quote_tweet_id")
    public void setQuoteTweetId(String quoteTweetId) {
        this.quoteTweetId = quoteTweetId;
    }
    @JsonGetter("quote_tweet_id")
    public String getQuoteTweetId() {
        return this.quoteTweetId;
    }
    @JsonSetter("reply")
    public void setReply(TweetReply reply) {
        this.reply = reply;
    }
    @JsonGetter("reply")
    public TweetReply getReply() {
        return this.reply;
    }
    @JsonSetter("reply_settings")
    public void setReplySettings(String replySettings) {
        this.replySettings = replySettings;
    }
    @JsonGetter("reply_settings")
    public String getReplySettings() {
        return this.replySettings;
    }
    @JsonSetter("text")
    public void setText(String text) {
        this.text = text;
    }
    @JsonGetter("text")
    public String getText() {
        return this.text;
    }
}
