/**
 * TweetDeleteResponseMessage automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.sdkfabric.twitter;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;
public class TweetDeleteResponseMessage {
    private boolean deleted;
    @JsonSetter("deleted")
    public void setDeleted(boolean deleted) {
        this.deleted = deleted;
    }
    @JsonGetter("deleted")
    public boolean getDeleted() {
        return this.deleted;
    }
}
