/**
 * TweetCreateResponseMessage automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.sdkfabric.twitter;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
public class TweetCreateResponseMessage {
    private String id;
    private String text;
    @JsonSetter("id")
    public void setId(String id) {
        this.id = id;
    }
    @JsonGetter("id")
    public String getId() {
        return this.id;
    }
    @JsonSetter("text")
    public void setText(String text) {
        this.text = text;
    }
    @JsonGetter("text")
    public String getText() {
        return this.text;
    }
}
