/**
 * TweetReply automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.sdkfabric.twitter;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
public class TweetReply {
    private java.util.List<String> excludeReplyUserIds;
    private String inReplyToTweetId;
    @JsonSetter("exclude_reply_user_ids")
    public void setExcludeReplyUserIds(java.util.List<String> excludeReplyUserIds) {
        this.excludeReplyUserIds = excludeReplyUserIds;
    }
    @JsonGetter("exclude_reply_user_ids")
    public java.util.List<String> getExcludeReplyUserIds() {
        return this.excludeReplyUserIds;
    }
    @JsonSetter("in_reply_to_tweet_id")
    public void setInReplyToTweetId(String inReplyToTweetId) {
        this.inReplyToTweetId = inReplyToTweetId;
    }
    @JsonGetter("in_reply_to_tweet_id")
    public String getInReplyToTweetId() {
        return this.inReplyToTweetId;
    }
}
