/**
 * TweetDelete automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.sdkfabric.twitter;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
public class TweetDelete {
    private Boolean deleted;
    @JsonSetter("deleted")
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }
    @JsonGetter("deleted")
    public Boolean getDeleted() {
        return this.deleted;
    }
}
