/**
 * UserCollection automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.sdkfabric.twitter;

import com.fasterxml.jackson.annotation.*;

public class UserCollection {
    private java.util.List<User> data;

    @JsonSetter("data")
    public void setData(java.util.List<User> data) {
        this.data = data;
    }

    @JsonGetter("data")
    public java.util.List<User> getData() {
        return this.data;
    }
}

