/**
 * User automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.sdkfabric.twitter;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
public class User {
    private String createdAt;
    private String id;
    private String name;
    private String pinnedTweetId;
    private String username;
    @JsonSetter("created_at")
    public void setCreatedAt(String createdAt) {
        this.createdAt = createdAt;
    }
    @JsonGetter("created_at")
    public String getCreatedAt() {
        return this.createdAt;
    }
    @JsonSetter("id")
    public void setId(String id) {
        this.id = id;
    }
    @JsonGetter("id")
    public String getId() {
        return this.id;
    }
    @JsonSetter("name")
    public void setName(String name) {
        this.name = name;
    }
    @JsonGetter("name")
    public String getName() {
        return this.name;
    }
    @JsonSetter("pinned_tweet_id")
    public void setPinnedTweetId(String pinnedTweetId) {
        this.pinnedTweetId = pinnedTweetId;
    }
    @JsonGetter("pinned_tweet_id")
    public String getPinnedTweetId() {
        return this.pinnedTweetId;
    }
    @JsonSetter("username")
    public void setUsername(String username) {
        this.username = username;
    }
    @JsonGetter("username")
    public String getUsername() {
        return this.username;
    }
}
