/**
 * BookmarkCreateResponseMessage automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.sdkfabric.twitter;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;
public class BookmarkCreateResponseMessage {
    private boolean bookmarked;
    @JsonSetter("bookmarked")
    public void setBookmarked(boolean bookmarked) {
        this.bookmarked = bookmarked;
    }
    @JsonGetter("bookmarked")
    public boolean getBookmarked() {
        return this.bookmarked;
    }
}
