/**
 * BookmarkCreateResponse automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.sdkfabric.twitter;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;
public class BookmarkCreateResponse {
    private BookmarkCreateResponseMessage data;
    @JsonSetter("data")
    public void setData(BookmarkCreateResponseMessage data) {
        this.data = data;
    }
    @JsonGetter("data")
    public BookmarkCreateResponseMessage getData() {
        return this.data;
    }
}
