/**
 * TweetDetails automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.sdkfabric.twitter;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;
import java.time.LocalDateTime;
public class TweetDetails {
    private String authorId;
    private String conversationId;
    private LocalDateTime createdAt;
    private List<String> editHistoryTweetIds;
    private String id;
    private String inReplyToUserId;
    private String text;
    @JsonSetter("author_id")
    public void setAuthorId(String authorId) {
        this.authorId = authorId;
    }
    @JsonGetter("author_id")
    public String getAuthorId() {
        return this.authorId;
    }
    @JsonSetter("conversation_id")
    public void setConversationId(String conversationId) {
        this.conversationId = conversationId;
    }
    @JsonGetter("conversation_id")
    public String getConversationId() {
        return this.conversationId;
    }
    @JsonSetter("created_at")
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }
    @JsonGetter("created_at")
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }
    @JsonSetter("edit_history_tweet_ids")
    public void setEditHistoryTweetIds(List<String> editHistoryTweetIds) {
        this.editHistoryTweetIds = editHistoryTweetIds;
    }
    @JsonGetter("edit_history_tweet_ids")
    public List<String> getEditHistoryTweetIds() {
        return this.editHistoryTweetIds;
    }
    @JsonSetter("id")
    public void setId(String id) {
        this.id = id;
    }
    @JsonGetter("id")
    public String getId() {
        return this.id;
    }
    @JsonSetter("in_reply_to_user_id")
    public void setInReplyToUserId(String inReplyToUserId) {
        this.inReplyToUserId = inReplyToUserId;
    }
    @JsonGetter("in_reply_to_user_id")
    public String getInReplyToUserId() {
        return this.inReplyToUserId;
    }
    @JsonSetter("text")
    public void setText(String text) {
        this.text = text;
    }
    @JsonGetter("text")
    public String getText() {
        return this.text;
    }
}
