/**
 * TweetPoll automatically generated by SDKgen please do not edit this file manually
 * @see https://sdkgen.app
 */

package org.sdkfabric.twitter;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;
public class TweetPoll {
    private int durationMinutes;
    private List<String> options;
    @JsonSetter("duration_minutes")
    public void setDurationMinutes(int durationMinutes) {
        this.durationMinutes = durationMinutes;
    }
    @JsonGetter("duration_minutes")
    public int getDurationMinutes() {
        return this.durationMinutes;
    }
    @JsonSetter("options")
    public void setOptions(List<String> options) {
        this.options = options;
    }
    @JsonGetter("options")
    public List<String> getOptions() {
        return this.options;
    }
}
